## This is the configuration file for Headroom.
## See https://github.com/vaclavsvejcar/headroom for more details.

run-mode: replace

source-paths:
  - src
  - example/src

excluded-paths: []

template-paths:
  - .headroom-templates

variables:
  project: Purescript Software Transactional Memory
  year: "2020"
  maintainer_name: Mohammad Hasani
  maintainer_email: the-dr-lazy@pm.me
  maintainer_comment: the-dr-lazy.github.io

license-headers:
  purescript:
    margin-after: 1
    block-comment:
      starts-with: "{-|"
      ends-with: "-}"

post-process:
  update-copyright:
    enabled: true
